[package]
name = "modbus-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "modbus-cli"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-serial = "5.4"
tokio-modbus = "0.14"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"